const schedule = {
  urlName: 'jinglejam2022',
  id: 'jinglejam2022',
  settings: {
    firstDayOfTheWeek: 1,
    showEmptyDays: true,
    showSlotTimes: true,
    startDate: '2022-12-01T11:00:00.000+0000',
    type: 'Special',
    appearance: 'WeekGrid',
  },
  name: 'Yogscast Jingle Jam 2022',
  visible: false,
  relations: {
    creators: [],
    podcasts: [],
    youtubeChannels: [],
    schedules: [],
    twitchChannels: [],
  },
  updatedAt: '2022-12-24T11:24:37.043537+0000',
  style: {
    slotStyle: {
      spacing: 2,
      borderRadius: 12,
      border: 'fff67932',
      background: 'ff1e95ef',
      elevation: 4,
    },
    timeStyle: {
      spacing: 4,
      borderWidth: 4,
      size: 60,
      elevation: 4,
      borderRadius: 12,
    },
    gridStyle: {
      dataSize: 60,
    },
  },
  schedule: {
    weeks: [
      {
        times: [
          {
            duration: 10800000000,
            start: '2022-01-01T11:00:00.000+0000',
          },
          {
            duration: 10800000000,
            start: '2022-01-01T14:00:00.000+0000',
          },
          {
            duration: 10800000000,
            start: '2022-01-01T17:00:00.000+0000',
          },
          {
            duration: 10800000000,
            start: '2022-01-01T20:00:00.000+0000',
          },
        ],
        days: [
          {
            slots: [
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=AMRiW0Tvems&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=1)\n\n[Twitch Vod](https://www.twitch.tv/videos/1667327674)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-01T11:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Office cam',
                duration: 10800,
                subtitle: 'Putting up the christmas tree',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff00bbe0', 'ff00aad9'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=wxEktU0AYkk&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=2)\n\n[Twitch Vod](https://www.twitch.tv/videos/1667327674?t=02h55m40s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-01T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Jingle Jam Hype Stream',
                duration: 10800,
                subtitle: 'Tom & Ben',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff0096d1', 'ff0086c9'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Dvsw8FJa8v3LjEXSXr9e', 'Hn8e1EgqFKg2RbJglY2x'],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=SFjS5rFn1sM&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=3&t=1228s)\n\n[Twitch VOD](https://www.twitch.tv/videos/1667327674?t=05h56m44s)\n\nLewis & Simon start the Jingle Jam with the traditional Jingle Cats stream where they watch fan made Jingle Cats videos. ![yogOOOO](https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_8facc7f6fe8e4b7499a96d9b7878f3c9/animated/light/1.0)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-01T17:00:00.000+0000',
                gridTileSize: 1,
                title: 'Jingle Cats',
                type: 'special',
                duration: 10800,
                subtitle: 'Lewis & Simon',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff0078c2', 'ff0066ba'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Gq7a6r1Pq0loxIUiNk8v', 'QLpFsapfyzIU4TYdVmjM'],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=h6Cnk9LSbtc&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=4)\n\n[Twitch VOD](https://www.twitch.tv/videos/1667327674?t=09h08m08s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-01T20:00:00.000+0000',
                gridTileSize: 1,
                title: 'Christmas Trains',
                type: 'special',
                duration: 10800,
                subtitle: 'Lewis, Duncan & Friends',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff0059b3', 'ff004dab'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'Dvsw8FJa8v3LjEXSXr9e',
                    '8K6EIOpBvb6ROSHWHx9Q',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'deBUVdSqWrH6FwlXPe2m',
                    'AcCWZMmDMrc7G9CnRchz',
                    'MYZPOwKsujCZbtPEJtBG',
                    'AZGGyF9uschXdM8gGB1v',
                    '3fNrixu9cDhggDXyLTwG',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
            ],
            dayOfWeek: 1,
            start: '2022-12-01T11:00:00.000+0000',
          },
          {
            slots: [
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=tI0tlNbX2Nw&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=5)\n\n[Twitch VOD](https://www.twitch.tv/videos/1668134096?t=00h34m55s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-02T11:00:00.000+0000',
                gridTileSize: 1,
                title: 'Switch Sports',
                type: 'special',
                duration: 10800,
                subtitle: 'RTGame Lewis Spiff Boba',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffd900', 'ffffd000'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'Tm2dvIIhVA3xb7nH19jJ',
                    'MYZPOwKsujCZbtPEJtBG',
                    'yAmEX9kxAZTdKzwQcIsy',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=mt_sypaJ0t8&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=6)\n\n[Twitch VOD](https://www.twitch.tv/videos/1668134096?t=03h38m54s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-02T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Plate Up',
                duration: 10800,
                subtitle: 'Massive Multiplayer',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffc800', 'ffffbf00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541', '26538483'],
                  creators: [
                    'vz0XWPLfxV9gFyChCgMO',
                    '0w4JSboJK6RdTDmDKoYL',
                    'sMGdgzZrZP8c68C0pFfU',
                    'Gz3S1VJlA6iPISXuIl7p',
                    'zwBpk82qRo4y2Sf5Nvlf',
                    'f2tAtl8eBRTtKsqzQQoC',
                    'dvynb4nu7GmqelY4HW3f',
                    'TGDsE9jQPa9WXOOgcmFm',
                    '8K6EIOpBvb6ROSHWHx9Q',
                    '6oSnPSBKF79EBwS1G5DF',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    '4ty8OfAA0hoXSV6trUY9',
                    'WvavBOeHzCXZPBzahkRX',
                    'MsNyFTyL0zikJ4zKOZm2',
                    'deBUVdSqWrH6FwlXPe2m',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=N0IIBW0WaBU&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=7)\n\n[Twitch VOD](https://www.twitch.tv/videos/1668134096?t=06h42m27s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-02T17:00:00.000+0000',
                gridTileSize: 1,
                title: 'Mario Kart Tournament',
                type: 'special',
                duration: 10800,
                subtitle: 'Hosted By Ravs',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffb700', 'ffffae00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'vz0XWPLfxV9gFyChCgMO',
                    'MsNyFTyL0zikJ4zKOZm2',
                    'f2tAtl8eBRTtKsqzQQoC',
                    'eE4FNKcFiBhoc3jFb9Fo',
                    'Tm2dvIIhVA3xb7nH19jJ',
                    'WvavBOeHzCXZPBzahkRX',
                    '8K6EIOpBvb6ROSHWHx9Q',
                    '5h6PnMWEghJSDaS5ZNbc',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=4ef7-Zpehm4&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=8)\n\n[Twitch VOD 1](https://www.twitch.tv/videos/1668469279)\n\n[Twitch VOD 1](https://www.twitch.tv/videos/1668524281)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-02T20:00:00.000+0000',
                gridTileSize: 1,
                title: 'Protessional Strem',
                type: 'special',
                duration: 10800,
                subtitle: 'Nilesy Zylus Rythian',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffa600', 'ffff9d00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    '5h6PnMWEghJSDaS5ZNbc',
                    'uuZ2P6KPhmLVGc7ZjWXR',
                    'deBUVdSqWrH6FwlXPe2m',
                    'WvavBOeHzCXZPBzahkRX',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
            ],
            dayOfWeek: 2,
            start: '2022-12-02T11:00:00.000+0000',
          },
          {
            slots: [
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=H3p3dHKP5Vs&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=9)\n\n[Twitch VOD](https://www.twitch.tv/videos/1669027004?t=00h39m38s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-03T11:00:00.000+0000',
                gridTileSize: 1,
                title: 'Puzzle Sisters',
                type: 'special',
                duration: 10800,
                subtitle: 'Bouphe & Osie',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffa7cc00', 'ff8bc200'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['G2xAxM8JBwtNIojLq1cE', 'MsNyFTyL0zikJ4zKOZm2'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=NtlEUNbgArA&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=12)\n\n[Twitch VOD](https://www.twitch.tv/videos/1669027004?t=03h38m00s)\n\nCute games with Kirsty & Briony\n\n![brionyKirsty](https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_63a898e8f71a4992a833b0ea5dddd854/static/light/2.0)![kirstBriony](https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_593306176ab34b45984d185549b1a278/static/light/2.0)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-03T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Cute Corner',
                duration: 10800,
                subtitle: 'Briony & Kirsty',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff74b800', 'ff5fad00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Gz3S1VJlA6iPISXuIl7p', 'zwBpk82qRo4y2Sf5Nvlf'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=ZJlJYUlu4SE&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=19)\n\n[Twitch VOD](https://www.twitch.tv/videos/1669027004?t=06h37m19s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-03T17:00:00.000+0000',
                gridTileSize: 1,
                title: "Simon's Important Videos",
                type: 'special',
                duration: 10800,
                subtitle: 'Simon Tom Harry Gee',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff49a300', 'ff389900'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'zFdYfSFj4efXLheSHG5Z',
                    '6oSnPSBKF79EBwS1G5DF',
                    'QLpFsapfyzIU4TYdVmjM',
                    'Hn8e1EgqFKg2RbJglY2x',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube VOD (Simon POV)](https://www.youtube.com/watch?v=uRsJ3zdfjsw&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=15)\n\n[Twitch VOD](https://www.twitch.tv/videos/1669423253)\n\n## Teams\n\n- Team Yellow: [Ravs](), Kirsty, Briony\n- Team Blue: [Ben](), Duncan, Osie\n- Team Red: [Simon](), Lewis, Gee\n- Team Green: Mango, Lolip, Sarah\n',
                showYoutubeIcon: false,
                visible: true,
                showHighlightIcon: true,
                start: '2022-12-03T20:00:00.000+0000',
                gridTileSize: 1,
                title: 'Minecraft Bingo',
                type: 'special',
                duration: 10800,
                subtitle: 'Hosted by Harry & Shadow',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff288f00', 'ff188500'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['68525019', '38167015', '21069037', '150004439', '26574506', '20786541'],
                  creators: [
                    '6oSnPSBKF79EBwS1G5DF',
                    'f2tAtl8eBRTtKsqzQQoC',
                    'vz0XWPLfxV9gFyChCgMO',
                    'QLpFsapfyzIU4TYdVmjM',
                    'MsNyFTyL0zikJ4zKOZm2',
                    'Gz3S1VJlA6iPISXuIl7p',
                    'TGDsE9jQPa9WXOOgcmFm',
                    'Dvsw8FJa8v3LjEXSXr9e',
                    '8K6EIOpBvb6ROSHWHx9Q',
                    'zMMAq6kg87R8WsHUS3s0',
                    'zFdYfSFj4efXLheSHG5Z',
                    'zwBpk82qRo4y2Sf5Nvlf',
                    'Gq7a6r1Pq0loxIUiNk8v',
                  ],
                  schedules: [],
                },
                showTwitchIcon: false,
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=zel6l9-bmrk&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=16)\n\n[Twitch VOD](https://www.twitch.tv/videos/1669608016)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-03T23:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Jingleathon',
                duration: 10800,
                subtitle: 'Pedguin & Ravs',
                style: {
                  border: 'fff67932',
                  elevation: 4,
                  spacing: 2,
                  borderRadius: 12,
                  background: 'ff188500',
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff188500', 'ff188500'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['vz0XWPLfxV9gFyChCgMO', '0w4JSboJK6RdTDmDKoYL'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
            ],
            dayOfWeek: 3,
            start: '2022-12-03T11:00:00.000+0000',
          },
          {
            slots: [
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=pZDb4isCBdU&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=20)\n\n[Twitch VOD](https://www.twitch.tv/videos/1670020081?t=00h41m53s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-04T11:00:00.000+0000',
                gridTileSize: 1,
                title: 'Game Hard',
                type: 'special',
                duration: 10800,
                subtitle: 'Mango & Daltos',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['fffc7600', 'fffa6800'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['AZGGyF9uschXdM8gGB1v', 'zMMAq6kg87R8WsHUS3s0'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=ggvnLTZDpl4&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=17)\n\n[Twitch VOD](https://www.twitch.tv/videos/1670020081?t=03h37m50s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-04T14:00:00.000+0000',
                gridTileSize: 1,
                title: 'Map Master',
                type: 'special',
                duration: 10800,
                subtitle: 'Potato & Spiff',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['fff75f00', 'fff55200'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['MYZPOwKsujCZbtPEJtBG', 'AcCWZMmDMrc7G9CnRchz'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=1nPbTZ275n0&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=24)\n\n[Twitch VOD](https://www.twitch.tv/videos/1670293623)\n\n## Teams\n\n- Duncan, Osie, Boba, Pedguin\n\n- Ben, Tom, Lewis, Pyrion\n\n- Tom B, Craig, Mat, Josh\n\n- Harry, "Lydia", Ravs, Sarah\n\n- Briony, Kirsty, Zylus, Mousie\n\n- RT, Spiff, Lolip, Mango\n',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-04T17:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: "Simon Clark's Yogs Challenges",
                duration: 10800,
                subtitle: 'University Challenge Parody',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['fff24900', 'fff03c00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'jP4KqZEefrAj53jHZ8HO',
                    '8K6EIOpBvb6ROSHWHx9Q',
                    'MsNyFTyL0zikJ4zKOZm2',
                    'yAmEX9kxAZTdKzwQcIsy',
                    '0w4JSboJK6RdTDmDKoYL',
                    'Dvsw8FJa8v3LjEXSXr9e',
                    'Hn8e1EgqFKg2RbJglY2x',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'o1gdP5407amAmS5vEXvP',
                    '6oSnPSBKF79EBwS1G5DF',
                    'vz0XWPLfxV9gFyChCgMO',
                    'Gz3S1VJlA6iPISXuIl7p',
                    'zwBpk82qRo4y2Sf5Nvlf',
                    '5h6PnMWEghJSDaS5ZNbc',
                    'dvynb4nu7GmqelY4HW3f',
                    'Tm2dvIIhVA3xb7nH19jJ',
                    'MYZPOwKsujCZbtPEJtBG',
                    'TGDsE9jQPa9WXOOgcmFm',
                    'zMMAq6kg87R8WsHUS3s0',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=-ive8iR030I&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=25)\n\n[Twitch VOD](https://www.twitch.tv/videos/1670507089)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-04T20:00:00.000+0000',
                gridTileSize: 1,
                title: 'Canadian Evening',
                type: 'special',
                duration: 10800,
                subtitle: 'Shadow & Alex',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffed2f00', 'ffeb2700'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['3fNrixu9cDhggDXyLTwG', 'f2tAtl8eBRTtKsqzQQoC'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
            ],
            dayOfWeek: 4,
            start: '2022-12-04T11:00:00.000+0000',
          },
          {
            slots: [
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=wVEiMeC39Ww&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=26)\n\n[Twitch VOD](https://www.twitch.tv/videos/1670906792?t=00h36m46s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-05T11:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Co-op Mayham',
                duration: 10800,
                subtitle: 'Zylus & Mousie',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff00e8c5', 'ff00e3b9'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['dvynb4nu7GmqelY4HW3f', '5h6PnMWEghJSDaS5ZNbc'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=Rin9zLRlQ3I&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=27)\n\n[Twitch VOD](https://www.twitch.tv/videos/1670906792?t=03h47m02s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-05T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Cozy Boardgames',
                duration: 10800,
                subtitle: 'Gee Lolip Alex Lolies & more',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff00deae', 'ff00d9a3'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'L9AyK1KaHcULKJMvAHcF',
                    'zFdYfSFj4efXLheSHG5Z',
                    'zwBpk82qRo4y2Sf5Nvlf',
                    'TGDsE9jQPa9WXOOgcmFm',
                    'zMMAq6kg87R8WsHUS3s0',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=mN457FGQwmI&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=28)\n\n[Twitch VOD](https://www.twitch.tv/videos/1670906792?t=06h37m42s)\n\n30% tech difficulties + 30% Gin + 30% Salt + 10% Civ = Yogs JJ Civ Stream\n\n\n## Teams\n\n- Lewis, Rythian, Spiff, Pyrion\n- Potato, Duncan, Alex, Ben\n',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-05T17:00:00.000+0000',
                gridTileSize: 2,
                type: 'special',
                title: 'Civ: Salt & Strategy',
                duration: 21600,
                subtitle: 'Lewis Duncan Spiff Ben Rythian, Pyrion Alex & Potato ',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff00d498', 'ff00cf8d'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'Dvsw8FJa8v3LjEXSXr9e',
                    '8K6EIOpBvb6ROSHWHx9Q',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'deBUVdSqWrH6FwlXPe2m',
                    'MYZPOwKsujCZbtPEJtBG',
                    '3fNrixu9cDhggDXyLTwG',
                    'AcCWZMmDMrc7G9CnRchz',
                    'o1gdP5407amAmS5vEXvP',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
            ],
            dayOfWeek: 5,
            start: '2022-12-05T11:00:00.000+0000',
          },
          {
            slots: [
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=hS6RizlEJ9E&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=29)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-06T11:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Dark Mysteries',
                duration: 10800,
                subtitle: 'Sips & Lydia',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['fff74acc', 'fff23fbf'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541', '26538483'],
                  creators: ['eE4FNKcFiBhoc3jFb9Fo', '4ty8OfAA0hoXSV6trUY9'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: false,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=QfOVPEMcpx0&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=32)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-06T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Tom & Wheelboy',
                duration: 10800,
                subtitle: 'The Boy Returns',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffed34b3', 'ffe82aa5'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'Hn8e1EgqFKg2RbJglY2x',
                    'zFdYfSFj4efXLheSHG5Z',
                    'eE4FNKcFiBhoc3jFb9Fo',
                    'dvynb4nu7GmqelY4HW3f',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  "[Youtube VOD](https://www.youtube.com/watch?v=3IOv7i2QOek&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=33)\n\nHat Films try to make music for charity.\nMaybe the continue last years story or maybe start something new.\n\n---\n\nLet's be honest.\n\nThere might be tech problems ![hatTech](https://static-cdn.jtvnw.net/emoticons/v2/306309899/static/light/1.0)\n\nThey'll be a bit ![Late](https://static-cdn.jtvnw.net/emoticons/v2/306309588/static/light/1.0) and go until past midnight. \nPoor Sam...\n",
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-06T17:00:00.000+0000',
                gridTileSize: 2,
                type: 'special',
                title: 'Hat Films Christmas Album',
                duration: 21600,
                subtitle: "The boys spend six hours making 'music' for an 'album'",
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffe32098', 'ffde168b'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Hz3L8GFTsM0EFg0caGoG'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
            ],
            dayOfWeek: 6,
            start: '2022-12-06T11:00:00.000+0000',
          },
          {
            slots: [
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=88mixSmwbhw&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=35)\n\n[Twitch Vod](https://www.twitch.tv/videos/1672594289?t=00h35m28s)\n\nPyrion shouts at Daf for 3 hours.  \n\n![flaxRage](https://static-cdn.jtvnw.net/emoticons/v2/943854/static/light/2.0)\n\n\n### Game 2\n\n- Rythian, Alister, Briony, Zylus, Breeh\n- Josh, Mike, Daf, Ali, Mamopato\n\n### Game 2\n- Joe & Friends\n- Sips, Ravs, Harry, Duncan Rythin+Zylus\n\n### Game 3\n- Daf & Bots\n- Mousie, Boba, Osie, Jack, Sarah',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-07T11:00:00.000+0000',
                gridTileSize: 1,
                title: 'Scrub Dota inhouse',
                type: 'special',
                duration: 10800,
                subtitle: 'Lewis Sips Joe Daf & Pyrion',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffa600', 'ffff9100'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541', '26538483'],
                  creators: [
                    'ShFoVukMUs1HAf2YryPl',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'Zf19FbodO1Alu5gfLykf',
                    'o1gdP5407amAmS5vEXvP',
                    '4ty8OfAA0hoXSV6trUY9',
                    'Gz3S1VJlA6iPISXuIl7p',
                    'deBUVdSqWrH6FwlXPe2m',
                    'WvavBOeHzCXZPBzahkRX',
                    '5h6PnMWEghJSDaS5ZNbc',
                    'yAmEX9kxAZTdKzwQcIsy',
                    '8K6EIOpBvb6ROSHWHx9Q',
                    '6oSnPSBKF79EBwS1G5DF',
                    'dvynb4nu7GmqelY4HW3f',
                    'vz0XWPLfxV9gFyChCgMO',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=hNUJvBMJKBY&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=34)\n\n[Twitch VOD](https://www.twitch.tv/videos/1672594289?t=03h42m21s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-07T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Cursedcraft',
                duration: 10800,
                subtitle: 'Simon & Gee',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffff7b00', 'ffff6a00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['zFdYfSFj4efXLheSHG5Z', 'QLpFsapfyzIU4TYdVmjM'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: false,
                markdownDesc: '[Twitch VOD](https://www.twitch.tv/videos/1672594289?t=06h42m01s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-07T17:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Feed a cow for christmas',
                duration: 10800,
                subtitle: 'Farming sim',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffff5500', 'ffff4000'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    '8K6EIOpBvb6ROSHWHx9Q',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'vz0XWPLfxV9gFyChCgMO',
                    'MsNyFTyL0zikJ4zKOZm2',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=u4PJpFRkapM&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=36)\n\n[Twitch VOD](https://www.twitch.tv/videos/1672938764)\n\n*In the dark, but not without rainbows bright! The gays are gathering for a jingle drive into the night* \n\nFionn & Shasskor (Fizone discord) Nov 30th 2022\n\n\n<center>\n\n![zoeyFZ1](https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_8eb09b9213ec40b18638c3ba12ff9636/static/light/2.0)![zoeyFZ2](https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_f817ddeb7edf457b8c1149580db93123/static/light/2.0)\n\n</center>\n',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-07T20:00:00.000+0000',
                gridTileSize: 1,
                title: 'Fizone After Dark',
                type: 'special',
                duration: 10800,
                subtitle: '',
                style: {
                  background: 'ffffffff',
                  linearGradient: {
                    end: {
                      x: 1,
                      y: 1,
                    },
                    begin: {
                      x: -1,
                      y: -1,
                    },
                    colors: ['ffffb1b0', 'ffffdfbe', 'ffffffbf', 'ffb4f0a7', 'ffa9d1f7', 'ffcc99ff'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['sMGdgzZrZP8c68C0pFfU', 'HkZh9sasvBrpZ4r22Sb3'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
            ],
            dayOfWeek: 7,
            start: '2022-12-07T11:00:00.000+0000',
          },
        ],
      },
      {
        times: [
          {
            duration: 10800000000,
            start: '2022-01-01T11:00:00.000+0000',
          },
          {
            duration: 10800000000,
            start: '2022-01-01T14:00:00.000+0000',
          },
          {
            duration: 10800000000,
            start: '2022-01-01T17:00:00.000+0000',
          },
          {
            duration: 10800000000,
            start: '2022-01-01T20:00:00.000+0000',
          },
        ],
        days: [
          {
            slots: [
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=3m6m9kxeWTM&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=37)\n\n[Twitch VOD](https://www.twitch.tv/videos/1673471320?t=00h40m41s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-08T11:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Hangover Hangout',
                duration: 10800,
                subtitle: 'Duncan & Osie',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff00bbe0', 'ff00aad9'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['8K6EIOpBvb6ROSHWHx9Q', 'MsNyFTyL0zikJ4zKOZm2'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=JfmT9dFIOSc&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=40)\n\n[Twitch VOD](https://www.twitch.tv/videos/1673471320?t=03h41m54s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-08T14:00:00.000+0000',
                gridTileSize: 1,
                title: "Pedguin's Pre Poker Party",
                type: 'special',
                duration: 10800,
                subtitle: 'Pedguin Plus Pals',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff0096d1', 'ff0086c9'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['0w4JSboJK6RdTDmDKoYL', 'yAmEX9kxAZTdKzwQcIsy', 'zFdYfSFj4efXLheSHG5Z'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=2cFVRGRdf4A&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=42)\n\n[Youtube VOD Table Chat](https://www.youtube.com/watch?v=rz7tYaLiQCY&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=43)\n\n[Twitch VOD](https://www.twitch.tv/videos/1673471320?t=07h23m40s)\n\n## Tables\n### Table 1\n- Daf, Duncan, Breeh, Osie, Lewis, Zylus\n\n### Table 2\n- Joe, Harry, Alex, Ravs, Kirsty, Mousie\n\n### Table 3\n- Lydia, Rythian, Boba, Sarah, Lolip, Nilesy\n\n## Final\n- Lydia (The Grand Appeal)\n- Zylus (Dogs for Autism)\n- Kirsty (Huntingtons Disease Association)\n- Ravs (Special Olympics GB)\n- Osie (Movember)\n- Nilesy (WDC)\n',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-08T17:30:00.000+0000',
                gridTileSize: 2,
                type: 'special',
                title: 'Poker Night',
                duration: 21600,
                subtitle: 'Pyrion Tom & many more Prize Pool by Displate',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff0078c2', 'ff0066ba'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541', '416016021'],
                  creators: [
                    'o1gdP5407amAmS5vEXvP',
                    'Hn8e1EgqFKg2RbJglY2x',
                    'ShFoVukMUs1HAf2YryPl',
                    '8K6EIOpBvb6ROSHWHx9Q',
                    'WvavBOeHzCXZPBzahkRX',
                    'MsNyFTyL0zikJ4zKOZm2',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    '5h6PnMWEghJSDaS5ZNbc',
                    'Zf19FbodO1Alu5gfLykf',
                    '6oSnPSBKF79EBwS1G5DF',
                    'L9AyK1KaHcULKJMvAHcF',
                    'vz0XWPLfxV9gFyChCgMO',
                    'zwBpk82qRo4y2Sf5Nvlf',
                    'dvynb4nu7GmqelY4HW3f',
                    'eE4FNKcFiBhoc3jFb9Fo',
                    'yAmEX9kxAZTdKzwQcIsy',
                    'TGDsE9jQPa9WXOOgcmFm',
                    'uuZ2P6KPhmLVGc7ZjWXR',
                    'deBUVdSqWrH6FwlXPe2m',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
            ],
            dayOfWeek: 1,
            start: '2022-12-08T11:00:00.000+0000',
          },
          {
            slots: [
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=WO0Aq7AzMbE&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=44)\n\n[Twitch VOD](https://www.twitch.tv/videos/1674336277?t=00h37m37s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-09T11:00:00.000+0000',
                gridTileSize: 1,
                title: 'Other Worlds',
                type: 'special',
                duration: 10800,
                subtitle: 'Briony & Zylus',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffd900', 'ffffd000'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Gz3S1VJlA6iPISXuIl7p', '5h6PnMWEghJSDaS5ZNbc'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=zT4bhzv5DvY&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=47)\n\n[Twitch VOD](https://www.twitch.tv/videos/1674336277?t=03h46m32s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-09T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Fighting Fantasy',
                duration: 10800,
                subtitle: 'Lewis Simon Nina & Jack',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffc800', 'ffffbf00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Gq7a6r1Pq0loxIUiNk8v', 'QLpFsapfyzIU4TYdVmjM'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc: '[Twitch VOD](https://www.twitch.tv/videos/1674336277?t=06h50m32s)',
                showYoutubeIcon: false,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-09T17:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Scultping the Yogscast',
                duration: 10800,
                subtitle: 'With AARDMAN',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffb700', 'ffffae00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['yAmEX9kxAZTdKzwQcIsy', 'Gz3S1VJlA6iPISXuIl7p', 'MsNyFTyL0zikJ4zKOZm2'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=09Bm3YucugU&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=48)\n\n[Twitch VOD](https://www.twitch.tv/videos/1674336277?t=09h43m33s)\n\n## Teams\n\n### Game 1:\n- Duncan, Boba, Ravs, Sarah, Daltos\n- Zylus, Mousie, Mango, Breeh, Kirsty\n\n### Game 2:\n- Potato, Digby, Martyn, Lewis, Briony\n- Joe, Wilson, Jack, Rythian, Lolip',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-09T20:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'CSGO Scrub Major',
                duration: 10800,
                subtitle: 'Hosted by Spiff & Pyrion',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffa600', 'ffff9d00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    '8K6EIOpBvb6ROSHWHx9Q',
                    'yAmEX9kxAZTdKzwQcIsy',
                    'vz0XWPLfxV9gFyChCgMO',
                    'AZGGyF9uschXdM8gGB1v',
                    '5h6PnMWEghJSDaS5ZNbc',
                    'dvynb4nu7GmqelY4HW3f',
                    'zMMAq6kg87R8WsHUS3s0',
                    'WvavBOeHzCXZPBzahkRX',
                    'zwBpk82qRo4y2Sf5Nvlf',
                    'AcCWZMmDMrc7G9CnRchz',
                    'EoUzF0nQQGdpY9NlZfeU',
                    'Zf19FbodO1Alu5gfLykf',
                    'TGDsE9jQPa9WXOOgcmFm',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'Gz3S1VJlA6iPISXuIl7p',
                    'deBUVdSqWrH6FwlXPe2m',
                    'IOdPOlLaB7zFHvsuvVwu',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
            ],
            dayOfWeek: 2,
            start: '2022-12-09T11:00:00.000+0000',
          },
          {
            slots: [
              {
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=qx8eOt5z7EM&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=50)\n\n[Twitch VOD](https://www.twitch.tv/videos/1675235787?t=00h36m24s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-10T11:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Breakfest Mixup',
                duration: 10800,
                subtitle: 'Mousie & Breeh',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffa7cc00', 'ff8bc200'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['WvavBOeHzCXZPBzahkRX', 'dvynb4nu7GmqelY4HW3f'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube VOD](https://www.youtube.com/watch?v=DXQYXHWczAs&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=53)\n\n[Twitch VOD](https://www.twitch.tv/videos/1675235787?t=03h40m24s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-10T14:00:00.000+0000',
                gridTileSize: 1,
                title: 'Tactic games',
                type: 'special',
                duration: 10800,
                subtitle: 'Rythian Zylus & Kirsty',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff74b800', 'ff5fad00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['deBUVdSqWrH6FwlXPe2m', '5h6PnMWEghJSDaS5ZNbc', 'zwBpk82qRo4y2Sf5Nvlf'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=H5PMK_xrZPM&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=56)\n\n[Twitch VOD](https://www.twitch.tv/videos/1675235787?t=06h40m22s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-10T17:00:00.000+0000',
                gridTileSize: 1,
                title: 'Everyone is santa',
                type: 'special',
                duration: 10800,
                subtitle: "Tom's Roleplay",
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff49a300', 'ff389900'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'Hn8e1EgqFKg2RbJglY2x',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'QLpFsapfyzIU4TYdVmjM',
                    'eE4FNKcFiBhoc3jFb9Fo',
                    'vz0XWPLfxV9gFyChCgMO',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Longest Johns Youtube Vod](https://www.youtube.com/watch?v=5Jd5Z_m4wdA&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=57)\n\n[Rust RP Youtube Vod](https://www.youtube.com/watch?v=otBLySLpDgQ&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=58)\n\n---\n\n[Longest John Twitch VOD](https://www.twitch.tv/videos/1675235787?t=09h47m06s)\n\n[Rust RP Twitch VOD](https://www.twitch.tv/videos/1675235787?t=10h55m46s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-10T20:00:00.000+0000',
                gridTileSize: 1,
                title: 'Longest John Singalong',
                type: 'special',
                duration: 14400,
                subtitle: 'Followd by Rust RP',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff288f00', 'ff188500'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['o1gdP5407amAmS5vEXvP', 'MYZPOwKsujCZbtPEJtBG', 'EoUzF0nQQGdpY9NlZfeU'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=omBPPcIbihU&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=59)\n\n[Twitch VOD](https://www.twitch.tv/videos/1675858946)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-11T00:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: "Harry's Vault Hunters Marathon",
                duration: 43200,
                subtitle: 'Minecraft Madness',
                style: {
                  border: 'fff67932',
                  elevation: 4,
                  spacing: 2,
                  borderRadius: 12,
                  background: 'ff1e95ef',
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff188500', 'ff188500'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['6oSnPSBKF79EBwS1G5DF'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
            ],
            dayOfWeek: 3,
            start: '2022-12-10T11:00:00.000+0000',
          },
          {
            slots: [
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=HhfCAHy9gtc&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=60)\n\n[Twitch VOD](https://www.twitch.tv/videos/1676166943?t=00h14m08s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-11T11:00:00.000+0000',
                gridTileSize: 1,
                title: 'Cutesy Chums',
                type: 'special',
                duration: 10800,
                subtitle: 'Pedguin & Daf',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['fffc7600', 'fffa6800'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['ShFoVukMUs1HAf2YryPl', '0w4JSboJK6RdTDmDKoYL'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=zGl9cE_cSNQ&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=63)\n\n[Twitch VOD](https://www.twitch.tv/videos/1676166943?t=03h09m07s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-11T14:00:00.000+0000',
                gridTileSize: 1,
                title: 'Friend Time',
                type: 'special',
                duration: 10800,
                subtitle: 'Bekki & Ped',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['fff75f00', 'fff55200'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['7tl19sOXgMq8ONpa0Wwc', '0w4JSboJK6RdTDmDKoYL'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=Ubs2h84hlKQ&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=66)\n\n[Twitch VOD](https://www.twitch.tv/videos/1676394889?t=00h01m24s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-11T17:00:00.000+0000',
                gridTileSize: 1,
                title: 'High rollers',
                type: 'special',
                duration: 10800,
                subtitle: 'Christmas special',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['fff24900', 'fff03c00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'Hz3L8GFTsM0EFg0caGoG',
                    'OxMCBocsLB1lXH5tQV6u',
                    'RuJTT0r57IGKXWtlHNVX',
                    'c9raygCH9eGa09OLB12t',
                    'vz0XWPLfxV9gFyChCgMO',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=6VXset5EilY&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=67)\n\n[Twitch VOD](https://www.twitch.tv/videos/1676531983?t=00h19m06s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-11T20:00:00.000+0000',
                gridTileSize: 1,
                title: "Lolip's Satisfactory",
                type: 'special',
                duration: 10800,
                subtitle: 'Lolipopg Ravs Shadow & Daltos',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffed2f00', 'ffeb2700'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'TGDsE9jQPa9WXOOgcmFm',
                    'vz0XWPLfxV9gFyChCgMO',
                    'f2tAtl8eBRTtKsqzQQoC',
                    'AZGGyF9uschXdM8gGB1v',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=VK0OmqNqddg&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=68)\n\n[Twitch VOD](https://www.twitch.tv/videos/1676531983?t=03h17m08s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-11T23:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Late Night Ranch Sim',
                duration: 10800,
                subtitle: 'Duncan Ravs & Friends',
                style: {
                  border: 'ffff1500',
                  background: 'ffff1500',
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    '8K6EIOpBvb6ROSHWHx9Q',
                    'vz0XWPLfxV9gFyChCgMO',
                    'MsNyFTyL0zikJ4zKOZm2',
                    '0w4JSboJK6RdTDmDKoYL',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: '',
              },
            ],
            dayOfWeek: 4,
            start: '2022-12-11T11:00:00.000+0000',
          },
          {
            slots: [
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=dryAWFSaqTE&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=69)\n\n[Twitch VOD](https://www.twitch.tv/videos/1677017533?t=00h27m56s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-12T11:00:00.000+0000',
                gridTileSize: 1,
                title: 'Dad Town',
                type: 'special',
                duration: 10800,
                subtitle: 'Ben & Sips',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff00e8c5', 'ff00e3b9'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Dvsw8FJa8v3LjEXSXr9e', '4ty8OfAA0hoXSV6trUY9'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=aejdSZ3UwQE&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=73)\n\n[Twitch VOD](https://www.twitch.tv/videos/1677017533?t=03h32m52s)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-12T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Chillout Clundle',
                duration: 10800,
                subtitle: 'Lewis & Zylus',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff00deae', 'ff00d9a3'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Gq7a6r1Pq0loxIUiNk8v', '5h6PnMWEghJSDaS5ZNbc'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=pRmXuC5gMkM&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=76&t=2s)\n\n[Twitch VOD](https://www.twitch.tv/videos/1677200946?t=00h11m28s)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-12T17:00:00.000+0000',
                gridTileSize: 1,
                title: 'IRL Plateup challenge',
                type: 'special',
                duration: 10800,
                subtitle: 'Hosted by Ben & Fionn',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff00d498', 'ff00cf8d'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'Dvsw8FJa8v3LjEXSXr9e',
                    'sMGdgzZrZP8c68C0pFfU',
                    'ShFoVukMUs1HAf2YryPl',
                    'TGDsE9jQPa9WXOOgcmFm',
                    'eE4FNKcFiBhoc3jFb9Fo',
                    '0w4JSboJK6RdTDmDKoYL',
                  ],
                  schedules: [],
                },
                showTwitchIcon: true,
                desc: 'Daf & Lydia vs Ped & Lolip',
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=CDdZ5IJglsY&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=77)\n\n[Twitch VOD](https://www.twitch.tv/videos/1677340260)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-12T20:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'MSPaint Fighting Fantasy',
                duration: 12600,
                subtitle: 'Nilesy Rythian Breeh',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ff00c983', 'ff00c479'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['uuZ2P6KPhmLVGc7ZjWXR', 'deBUVdSqWrH6FwlXPe2m', 'WvavBOeHzCXZPBzahkRX'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
              {
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=ruqEvIybwFQ&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=78)\n\n[Twitch VOD](https://www.twitch.tv/videos/1677496900)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-12T23:30:00.000+0000',
                gridTileSize: 1,
                title: 'Co-op Games',
                type: 'special',
                duration: 10800,
                subtitle: 'Shadow & Daltos',
                style: {
                  border: 'ff00c479',
                  elevation: 4,
                  spacing: 2,
                  borderRadius: 12,
                  background: 'ff00c479',
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541', '68525019'],
                  creators: ['AZGGyF9uschXdM8gGB1v', 'f2tAtl8eBRTtKsqzQQoC'],
                  schedules: [],
                },
                showTwitchIcon: true,
              },
            ],
            dayOfWeek: 5,
            start: '2022-12-12T11:00:00.000+0000',
          },
          {
            slots: [
              {
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=9Vz6lLzU1uw&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=79)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-13T11:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Save the world',
                duration: 10800,
                subtitle: 'Lewis & Ben',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['fff74acc', 'fff23fbf'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Gq7a6r1Pq0loxIUiNk8v', 'Dvsw8FJa8v3LjEXSXr9e'],
                  schedules: [],
                },
                showTwitchIcon: false,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=RNv8lRiluB8&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=82)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-13T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: '4 Player co-op games',
                duration: 10800,
                subtitle: 'Pedguin & Friends',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffed34b3', 'ffe82aa5'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    '0w4JSboJK6RdTDmDKoYL',
                    'sMGdgzZrZP8c68C0pFfU',
                    'TGDsE9jQPa9WXOOgcmFm',
                    'dvynb4nu7GmqelY4HW3f',
                  ],
                  schedules: [],
                },
                showTwitchIcon: false,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=tdVcJnSHAlY&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=85)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-13T17:00:00.000+0000',
                gridTileSize: 1,
                title: 'Hatfilms gameshow',
                type: 'special',
                duration: 10800,
                subtitle: 'Hatfilms vs Lewis Lydia.& Ravs',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffe32098', 'ffde168b'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'Hz3L8GFTsM0EFg0caGoG',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'eE4FNKcFiBhoc3jFb9Fo',
                    'vz0XWPLfxV9gFyChCgMO',
                  ],
                  schedules: [],
                },
                showTwitchIcon: false,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=UO8cBpc7LDU&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=86)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-13T20:00:00.000+0000',
                gridTileSize: 1,
                title: 'Terraria Hangout',
                type: 'special',
                duration: 10800,
                subtitle: 'Pedguin & Friends',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffd90d7d', 'ffd4046f'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541', '150004439'],
                  creators: [
                    '0w4JSboJK6RdTDmDKoYL',
                    'Ot78GPFYxZbxjK6On2CW',
                    'yAmEX9kxAZTdKzwQcIsy',
                    'Dvsw8FJa8v3LjEXSXr9e',
                    'ShFoVukMUs1HAf2YryPl',
                  ],
                  schedules: [],
                },
                showTwitchIcon: false,
              },
              {
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=4vcuv9BuSzc&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=87)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-13T23:00:00.000+0000',
                gridTileSize: 1,
                title: 'Elden Ring Co-op',
                type: 'special',
                duration: 10800,
                subtitle: 'Shadow & Osie',
                style: {
                  border: 'ffd4046f',
                  elevation: 4,
                  spacing: 2,
                  borderRadius: 12,
                  background: 'ffd4046f',
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['MsNyFTyL0zikJ4zKOZm2', 'f2tAtl8eBRTtKsqzQQoC'],
                  schedules: [],
                },
                showTwitchIcon: false,
              },
            ],
            dayOfWeek: 6,
            start: '2022-12-13T11:00:00.000+0000',
          },
          {
            slots: [
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=OBBoj4vz6NI&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=88)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-14T11:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: 'Space wars',
                duration: 10800,
                subtitle: 'Lewis & Ben',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffffa600', 'ffff9100'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Gq7a6r1Pq0loxIUiNk8v', 'Dvsw8FJa8v3LjEXSXr9e'],
                  schedules: [],
                },
                showTwitchIcon: false,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=0lAmOAd42mc&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=90)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-14T14:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: "Tech 'em up",
                duration: 10800,
                subtitle: 'Ben Harry & Lewis',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffff7b00', 'ffff6a00'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: ['Dvsw8FJa8v3LjEXSXr9e', '6oSnPSBKF79EBwS1G5DF', 'Gq7a6r1Pq0loxIUiNk8v'],
                  schedules: [],
                },
                showTwitchIcon: false,
                desc: '',
              },
              {
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=XrAfRaTD5AQ&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=93)',
                showYoutubeIcon: true,
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-14T17:00:00.000+0000',
                gridTileSize: 1,
                type: 'special',
                title: "Martyn's Minecraft",
                duration: 10800,
                subtitle: 'Martyn Boba Ravs & Mango',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffff5500', 'ffff4000'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'IOdPOlLaB7zFHvsuvVwu',
                    'yAmEX9kxAZTdKzwQcIsy',
                    'vz0XWPLfxV9gFyChCgMO',
                    'zMMAq6kg87R8WsHUS3s0',
                  ],
                  schedules: [],
                },
                showTwitchIcon: false,
              },
              {
                showYoutubeIcon: true,
                markdownDesc:
                  '[Youtube Vod](https://www.youtube.com/watch?v=FZE5hbefUaE&list=PLvSp-8FGBzxk_D9LnE2aoAwKaEjc4ku8j&index=94)',
                visible: true,
                showHighlightIcon: false,
                start: '2022-12-14T20:00:00.000+0000',
                gridTileSize: 1,
                title: 'Late Late Show',
                type: 'special',
                duration: 10800,
                subtitle: 'Rythian Nilesy Zylus & more',
                style: {
                  linearGradient: {
                    end: {
                      x: 0,
                      y: 1,
                    },
                    begin: {
                      x: 0,
                      y: -1,
                    },
                    colors: ['ffff2a00', 'ffff1500'],
                  },
                },
                id: '',
                relations: {
                  youtubeChannels: [],
                  podcasts: [],
                  twitchChannels: ['20786541'],
                  creators: [
                    'deBUVdSqWrH6FwlXPe2m',
                    'uuZ2P6KPhmLVGc7ZjWXR',
                    '5h6PnMWEghJSDaS5ZNbc',
                    'yAmEX9kxAZTdKzwQcIsy',
                    'WvavBOeHzCXZPBzahkRX',
                    'Gz3S1VJlA6iPISXuIl7p',
                    'AZGGyF9uschXdM8gGB1v',
                    'zwBpk82qRo4y2Sf5Nvlf',
                    'Gq7a6r1Pq0loxIUiNk8v',
                    'zMMAq6kg87R8WsHUS3s0',
                    'dvynb4nu7GmqelY4HW3f',
                    'vz0XWPLfxV9gFyChCgMO',
                    '0w4JSboJK6RdTDmDKoYL',
                    'HkZh9sasvBrpZ4r22Sb3',
                  ],
                  schedules: [],
                },
                showTwitchIcon: false,
              },
            ],
            dayOfWeek: 7,
            start: '2022-12-14T11:00:00.000+0000',
          },
        ],
      },
    ],
    times: [
      {
        duration: 10800000000,
        start: '2022-01-01T11:00:00.000+0000',
      },
      {
        duration: 10800000000,
        start: '2022-01-01T14:00:00.000+0000',
      },
      {
        duration: 10800000000,
        start: '2022-01-01T17:00:00.000+0000',
      },
      {
        duration: 10800000000,
        start: '2022-01-01T20:00:00.000+0000',
      },
    ],
  },
}
export default schedule
